### ISSUE TITLE
Unnecessary configuration?

### ISSUE THREAD

**Issue by mih** [christian-monch/datalad-compute#8]
I did not set the following config items that are mandated in the example instructions:

- `git config annex.security.allowed-url-schemes datalad-make`
- `git config annex.security.allow-unverified-downloads ACKTHPPT`

The latter is *only* needed to act on prospective computing records

The first one is not needed at all, it seems.

**Comment by christian-monch** [comment]
> I did not set the following config items that are mandated in the example instructions:
> 
> * `git config annex.security.allowed-url-schemes datalad-make`
> * `git config annex.security.allow-unverified-downloads ACKTHPPT`
> 
> The latter is _only_ needed to act on prospective computing records
> [...]

Good point, I changed the example instructions to reflect that.

> The first one is not needed at all, it seems.

The first one has to be set, if a compute-URL should be added to a key by git-annex.

**Comment by christian-monch** [comment]
After looking into this issue, it seems that the following configurations are not required, if a compute remote is initialized:

- `git config annex.security.allowed-url-schemes datalad-make`
- `git config annex.security.allowed-ip-addresses all`

The following configuration is only required, if the result of a speculative computation should be materialized via `datalad get`:

- `git config annex.security.allow-unverified-downloads ACKTHPPT`

The documentation was changed to reflect that in PR #29
